# Generated by Django 6.0 on 2025-12-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_created_at_expense_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', '🍔 Еда'), ('transport', '🚗 Транспорт'), ('entertainment', '🎬 Развлечения'), ('utilities', '🏠 Коммунальные услуги'), ('shopping', '🛍️ Покупки'), ('health', '🏥 Здоровье'), ('education', '📚 Образование'), ('other', '📦 Другое')], default='other', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
